argo-cd:
  global:
    domain: argocd.dev.local
  configs:
    secret:
      # htpasswd -nbBC 10 "" "mypassword"  | tr -d ':\n' | sed 's/$2y/$2a/'
      argocdServerAdminPassword: $2a$10$LrowgH0EEK9HZFeFE4.4HOH3aDCPrl3W2YM3I5wgwSabf2C.Sx7eO
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: argocd.dev.local
      path: /
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /